.catalog:
  name: defect-vote
  version: jgreat_vote-demo-web_defect-vote_1.1.5_1_8d0bc1be
  description: vote-demo-web
  uuid: defect-vote-1

vote-demo-web:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000

vote-demo-web-app:
  scale: 1
  health_check:
    port: 8001
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
