vote-demo-web:
  image: rancher/load-balancer-service
  ports:
    - 8001:8001
  links:
    - vote-demo-web-app:vote-demo-web-app

vote-demo-web-app:
  image: jgreat/vote-demo-web:jgreat_vote-demo-web_feature-pikachu-pikachu_1.0.0_2_c500be40
  expose:
    - 8001
  environment:
    RANCHER_SERVICE_DISCOVERY: 'true'
    LISTEN_PORT: 8001
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
