.catalog:
  name: feature-pikachu-pikachu
  version: jgreat_vote-demo-web_feature-pikachu-pikachu_1.0.0_2_c500be40
  description: vote-demo-web
  uuid: feature-pikachu-pikachu-1

vote-demo-web:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000

vote-demo-web-app:
  scale: 1
  health_check:
    port: 8001
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
