.catalog:
  name: drone-test3
  version: aymericDD_1dtouch-music_drone-test3_1.2.4_1_2a1199b8
  description: 1dtouch-music
  uuid: drone-test3-0

1dtouch-music:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    healthy_threshold: 2
    response_timeout: 2000

1dtouch-music-app:
  scale: 1
  health_check:
    port: 5000
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
